/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'iQiwen' at '18-5-3 上午10:04' with Gradle 2.6
 *
 * @author iQiwen, @date 18-5-3 上午10:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
